# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 18:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('numeroAsiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime(2017, 11, 2, 18, 17, 4, 496023, tzinfo=utc))),
                ('comentarios', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['Tipo'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaContable.Cuenta')),
                ('numeroAsiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaContable.Asiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='Tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sistemaContable.TipoCuenta'),
        ),
    ]
