# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistemaContable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='asiento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='Tipo',
            field=models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('P.N', 'Patrimonio Neto'), ('R.N', 'Resultado Negativo'), ('R.P', 'Resultado Positivo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='debe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='haber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.DeleteModel(
            name='TipoCuenta',
        ),
    ]
