# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaContable', '0002_auto_20171129_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
