# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librodiario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
