# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librodiario', '0002_auto_20171009_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.date(2017, 10, 9)),
        ),
    ]
