# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('librodiario', '0003_auto_20171009_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
