# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librodiario', '0004_auto_20171009_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='numeroAsiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
