# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librodiario', '0005_auto_20171009_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='Tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='librodiario.TipoCuenta'),
        ),
    ]
