# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librodiario', '0006_auto_20171009_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['Tipo']},
        ),
    ]
