# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('librodiario', '0007_auto_20171011_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['numeroAsiento']},
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='asiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
