# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librodiario', '0008_auto_20171018_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='debe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='haber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
