# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('librodiario', '0009_auto_20171020_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2017, 10, 24, 14, 16, 0, 570118, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='librodiario.Cuenta'),
        ),
    ]
