# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('librodiario', '0010_auto_20171024_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={},
        ),
        migrations.AlterField(
            model_name='asiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2017, 10, 28, 1, 37, 25, 916686, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movCuenta', to='librodiario.Cuenta'),
        ),
    ]
